import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1, 
        justifyContent: 'center', 
        alignItems: 'center',
        backgroundColor: '#F5F5F5', 
    },
    question: {
        width: "80%",
        fontSize: 20, 
        fontWeight: 'bold', 
        marginBottom: 20,
        color: '#003366', 
    },
    buttons: {
        width: '100%',
        backgroundColor: '#0055A4',
        textAlign: 'center',
        paddingTop: 5,
        paddingBottom: 8,
        paddingHorizontal: 5,
        borderRadius: 5,
        marginTop: 20,
        fontSize: 20,
        color: 'white',
        shadowColor: '#000', 
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 2,
    },
    buttonsFinalizar: {
        width: '80%',
        backgroundColor: '#003366', 
        textAlign: 'center',
        paddingTop: 5,
        paddingBottom: 8,
        paddingHorizontal: 5,
        borderRadius: 5,
        marginTop: 20,
        fontSize: 20,
        color: 'white',
        shadowColor: '#000', 
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 2,
    },
    buttonsAnterior: {
        width: '100%',
        backgroundColor: '#0055A4', 
        textAlign: 'center',
        paddingTop: 5,
        paddingBottom: 8,
        paddingHorizontal: 10,
        borderRadius: 5,
        marginTop: 20,
        fontSize: 20,
        color: 'white',
        shadowColor: '#000', 
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 2,
        elevation: 2,
    },
});
